### PR TITLE
394 display uploaded models does not work for vue3

### LINKED ISSUE #394: Display uploaded Models does not work for Vue3
Displaying uploaded Models in FIles tab does not work for Vue3 Frontend

Screenshot 2023-08-17 202927
Screenshot 2023-08-17 202951

### PR DESCRIPTION
**Pull request by MeisterSeSe**

### CODE REVIEW

File: frontendVue3/src/components/FeatureModelTable.vue [hunk 1]
```diff
@@ -283,47 +287,36 @@ const headers = [
         sortable: false,
     },
 ];
-const search = '';
-const removeLoading = false;
-const dialog = false;
+const search = ref('');
+const removeLoading = ref(false);
+const dialog = ref(false);
```
Comment (LukasOsti) [inline frontendVue3/src/components/FeatureModelTable.vue]: Looks good to me :)

But maybe remove not used variables.

Comment (MeisterSeSe) [reply frontendVue3/src/components/FeatureModelTable.vue]: Removed and also fixed tooltips for buttons.

**Review by LukasOsti — APPROVED** [review]
