### PR TITLE
fix editing/deleting constraints when highlighted

### LINKED ISSUE #344: Deleting highlighted constraints does not remove coloring in tree
How to reproduce:
1. create some constraint
2. press the chip of the constraint to highlight it in the tree
3. press the garbage can next to the constraint
4. result
    - expected: chip is removed and highlighting as well
    - actual: only chip is removed and highlighting stays
5. additional problem: the color seems to be still "reserved" for the removed chip. Usually when creating multiple constraints they recieve colors in this order: red -> orange -> blue-ish -> ...When creating a new constraint after this behavior it recieves the 2. color (orange) not the first one (red).

before delete:
image

after delete:
image

after addition of second constraint:
image

### PR DESCRIPTION
**Pull request by tomatenhans**
Trying to fix #344  and #345 with this PR.

Took some time to realize that the update event has to be emitted each time the constraints are edited/deleted.

~~The additional Problem mentioned in #344, with the reserved colors, is still WIP.~~

### CODE REVIEW

File: frontendVue3/src/components/Constraints.vue [hunk 1]
```diff
@@ -173,11 +173,16 @@ export default {
             }
             this.closeAddEditDialog();
             this.commandManager.execute(command);
+            this.$emit('update-feature-model');
         },
 
         deleteConstraint(constraint) {
+            if(constraint.isHighlighted){ //reset highlight to free up color
```
Comment (tomatenhans) [inline frontendVue3/src/components/Constraints.vue:180]: This works fine to workaround the Problem mentioned in #344, however has the drawback that undo/redo does not automatically highlight the deleted Constraint again.

**Review by LukasOsti — APPROVED** [review]
LGTM :)
